### ISSUE TITLE
Error when using new cli client: flag provided but not defined

### ISSUE THREAD

**Issue by sterankin** [transifex/cli#105]
I am currently migrating from the old Python cli, to the new Go client.

When doing a push/pull I am getting the following error message:

**_Incorrect Usage: flag provided but not defined: -no-interactive_**

We called the push and pull as follows:

```
tx push -s --skip --no-interactive
tx pull -a -f --mode sourceastranslation --skip --no-interactive
```

Is the --no-interactive no longer supported in the new version (TX Client, version=1.4.0).  The flag is still listed in the documentation at the very bottom of the Github page:  https://github.com/transifex/cli, as well as in the official docs:

https://developers.transifex.com/docs/using-the-client

However looking at the client code, it only seems to be supported when doing a `tx update.`

**Comment by codegaze** [comment]
Hello @sterankin. The`--no-interactive` is currently only supported in the `update` command and not to the other commands.

Is there a problem you faced while using `pull` or `push` with the absence of this flag?

**Comment by sterankin** [comment]
Previously the --no-interactive was used during a push or pull  when using a CI tool, which would skip any prompting.
From the docs:  https://docs.transifex.com/client/pull

```
--no-interactive: Don't require user input when forcing a push.
--no-interactive: Don't require user input when forcing a pull.
```

Are you saying that the new CLI version will not have any user prompts when pushing or pulling.   Since our process is fully automated within CI, we don't want any potential prompts to appear and the --no-interactive flag was used to prevent that.

**Comment by kbairak** [comment]
@sterankin 

> Are you saying that the new CLI version will not have any user prompts when pushing or pulling?

That is correct.

Furthermore, there is an undocumented flag (that you can view with `tx push/pull -h` nevertheless) called `--silent` to reduce the amount of output shown in CI environments.

Feel free to try it out and let us now if everything works out ok.
