### ISSUE TITLE
Error when using the new client to pull resources with `tx pull -l zh_CN --mode onlyreviewed --use-git-timestamps`

### ISSUE THREAD

**Issue by mendax1234** [transifex/cli#106]
It seems that two days ago, l can use `tx pull -l zh_CN --mode onlyreviewed --use-git-timestamps` to pull the resources from transifex. However, since two days ago, this line of code isn't adaptive. What's the problem? l see the the latest commit change was also two days ago? l believe some changes in this commit leads to this error.

And here is the error:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/62934294/195493808-35bc4121-242a-44e9-a29e-ba23e152c189.png">

**Comment by kbairak** [comment]
Hello @mendax1234,

Our latest release [v1.4.1](https://github.com/transifex/cli/releases/tag/v1.4.1) fixes this issue.

Thank you for bringing this to our attention.

**Comment by mendax1234** [comment]
> Hello @mendax1234,
> 
> Our latest release [v1.4.1](https://github.com/transifex/cli/releases/tag/v1.4.1) fixes this issue.
> 
> Thank you for bringing this to our attention.

Thanks! Furthermore, I want to use a specific version of Transifex to avoid the loss caused by the update. So, how should I proceed? Could you please provide some details? Thanks!

**Comment by kbairak** [comment]
It depends on your installation method:

- If you [downloaded the binary](https://github.com/transifex/cli#download-from-github-releases-linuxmacwindows) from the [releases page](https://github.com/transifex/cli/releases), then you can simply choose the version you are interested in

- If you want to use the [installation script](https://github.com/transifex/cli/releases), you can replace the occurrence of `master` in the URL with the version you want. For example

  ```
  curl -o- https://raw.githubusercontent.com/transifex/cli/v1.4.1/install.sh | bash
  ```

**Comment by mendax1234** [comment]
> It depends on your installation method:
> 
> * If you [downloaded the binary](https://github.com/transifex/cli#download-from-github-releases-linuxmacwindows) from the [releases page](https://github.com/transifex/cli/releases), then you can simply choose the version you are interested in
> * If you want to use the [installation script](https://github.com/transifex/cli/releases), you can replace the occurrence of `master` in the URL with the version you want. For example
>   ```
>   curl -o- https://raw.githubusercontent.com/transifex/cli/v1.4.1/install.sh | bash
>   ```

Got it! Thank you very much!
