### ISSUE TITLE
New client doesn't appear to use $HOME environment variable

### ISSUE THREAD

**Issue by Docteh** [transifex/cli#109]
GHA (GitHub Actions) sets HOME to /github/home

In a GHA script I do
```shell
cat << EOF > ~/.transifexrc
[https://www.transifex.com]
rest_hostname = https://rest.api.transifex.com
token         = $TRANSIFEX_API_TOKEN
EOF

```

Meanwhile the current tx client (1.4.0) is actually looking at /etc/passwd to find home directory.

```
(from an strace)
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/root/.transifexrc", O_RDONLY|O_CLOEXEC) = 3
```

End result is that I write a config but the client doesn't see.

**Comment by kbairak** [comment]
Hey @Docteh,

Our latest release [v1.4.1](https://github.com/transifex/cli/releases/tag/v1.4.1) fixes this issue.

Thank you for bringing this to our attention.
