### ISSUE TITLE
`tx push` and `tx pull` show the error `tx ERROR: not enough values to unpack (expected 2, got 1)`

### ISSUE THREAD

**Issue by arlindiDev** [transifex/cli#110]
The following command `tx push -s` shows the following error:
`tx ERROR: not enough values to unpack (expected 2, got 1)`

I just upgraded to the new version that supports the new config file format.

**Comment by kbairak** [comment]
Hey @arlindiDev,

In addition to what @codegaze said, to me this error message seems that it comes from a Python runtime and not a Go binary. Could you also show us the output of `tx -h` and `which tx`?

Thanks

**Comment by arlindiDev** [comment]
@kbairak sorry I fixed this issue. Transifex was updated and we were still using the old version of the cli client
