### ISSUE TITLE
Support for TX_TOKEN environment variable

### ISSUE THREAD

**Issue by m-aciek** [transifex/cli#116]
Hello,

I'm currently trying to migrate to new CLI. Old one had a helpful feature of reading the API key from environment variable, `TX_TOKEN`, instead of getting it from `--token` argument appended to every command. Would you consider supporting it?

[1] https://github.com/transifex/transifex-client/blob/902d6679ff4c1d454ae642c60050867908924a23/txclib/project.py#L112-L133

**Comment by Docteh** [comment]
I've been using TX_TOKEN for like `tx push -s` and `tx pull -t -a`

**Comment by m-aciek** [comment]
Ah, sorry -- my bad. I got mistaken while debugging my code. The environment variable works just fine for me. Closing the issue.
