### ISSUE TITLE
`tx pull -a -t` always returns `Aborted` when pulling translated files

### ISSUE THREAD

**Issue by luizfilho-hotmart** [transifex/cli#118]
I'm running `tx pull -a -t` to get translated files and it always returns `Aborted` with no error messages.

`tx -h`
```
NAME:
   tx - A new cli application

USAGE:
   tx [global options] command [command options] [arguments...]

VERSION:
   1.4.1
```

`which tx`
`/usr/local/bin/tx`

**Comment by kbairak** [comment]
Hey @luizfilho-hotmart,

I see that you closed this, but if you could give us a hint as to how we can reproduce this, we would appreciate this. Even if there was an error in the configuration that you since fixed, a simple 'Aborted' message is not a proper response by the cli.

Thanks

**Comment by luizfilho-hotmart** [comment]
Hello @kbairak,

This error occurred when the Transifex API was unstable. After the API instability normalize the translation files returned correctly. I didn't change the configuration.
