### ISSUE TITLE
Updated to version 1.4.0 getting an error

### ISSUE THREAD

**Issue by arlindiDev** [transifex/cli#121]
When running the following command:
`tx pull --force -l=de,en_GB,es,fr,it,nl,pl,pt_BR,sv`

I get the error below:

`It doesn't make sense to use the '--all' or '--language' flag without the '--translation' flag`

**Comment by codegaze** [comment]
Hello @arlindiDev, please update to the latest version (`1.4.1`). In  `1.4.0` we introduced a check that was causing this error. 

Feel free to close this one if everything is ok after updating.
