### ISSUE TITLE
There is no way to install a specific version of CLI with current bash installer

### ISSUE THREAD

**Issue by maximbircu** [transifex/cli#122]
### Background
I am using TX on my CI, for which the machine spins up automatically and installs the TX CLI every time I build a new image for it. Considering that the CLI is evolving actively at the moment, I would like to take control over the version that gets installed on my machine so that I don't have my logic broken due to new breaking changes from the latest version.

### Requirements
- Adjust https://github.com/transifex/cli/blob/f5475ffb4c267f320dc97ea2facb7ae4e1400e2d/install.sh to accept the TX version that should be installed as a parameter.
- If the parameter is not passed, the latest version should be installed.

### How to test
1. Run ./install.sh v1.4.0
2. Make sure "TX Client, version=1.4.0" gets printed on the last line in the output
3. Run ./install.sh
4. Make sure "TX Client, version=1.4.1" gets printed on the last line in the output

**Comment by codegaze** [comment]
Hey @maximbircu,
Again, thank you for your contribution! The change is now on `master`, so you and everyone else can use it! 👏
