### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by ekaterinashenets** [transifex/cli#132]
Hello!

We're using `curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash -s -- 1.4.1` command to install transifex client. Everything was clear yesterday, but today it fails with an error:
`tgzip: stdin: not in gzip format`. See screenshot

<img width="950" alt="image" src="https://user-images.githubusercontent.com/43377137/202430222-24ed1b1a-87fc-485b-ae21-da0e12d60354.png">

**Comment by codegaze** [comment]
Hey @ekaterinashenets, thanks for bringing this into our attention.

The version addition was merged today, so I'm not sure how you managed to get the version with the `https://raw.githubusercontent.com/transifex/cli/master/install.sh` url.

Either way, I think adding `v` as in `-- v1.4.1` should solve this issue :)

**Comment by ekaterinashenets** [comment]
@codegaze works for me, thanks!
