### ISSUE TITLE
tx add unable to add source file

### ISSUE THREAD

**Issue by chinomnsoawazie** [transifex/cli#146]
Hi 👋 

**What is happening**
While upgrading  from v2 API to v3, we are following the cli documentation and adding attributes to the `.tx/config` this way

` tx init `
` tx add \ `
` --file-filter=source_file_path \ `
` --type=XLIFF \ `
` --organization=my_organization \ `
` --project=project_name_in_may_organization \ `
` --resource=project_name_in_may_organization.filename \ `
` --resource-name=filename \ `
`  source_file_path.xlf `

**Expected**
The cli is able to add the source file to `.tx/config`

**Result**
The cli throws an error: "you need to add a Source File that exists".
The file exists as a cat of `source_file_path .xlf ` shows its contents

Environment:
cli version: `v1.6.4`

**Comment by chenrui333** [comment]
cc @codegaze

**Comment by codegaze** [comment]
Hello @chinomnsoawazie !

Thanks for providing steps to reproduce! I tried to follow what you described to see if there is something wrong with the `add` command and the result was the expected one.

<img width="692" alt="sample" src="https://user-images.githubusercontent.com/7371227/205350523-82ab07e3-f3fb-4452-8154-2275788baa18.png">


As a first action, I would suggest to make sure that you are in the project folder and you are providing a relative path to the project. The config file needs to work on multiple environments and not the specific machine, and this is why a relative path is needed. 

Feel free to close the issue if it is solved :)

**Comment by codegaze** [comment]
Hello @chinomnsoawazie, I will assume that the issue was resolved so I will close this one for now. 
If you still have problems with adding this file, please open it again!
