### ISSUE TITLE
Failed to push 

### ISSUE THREAD

**Issue by micke136** [transifex/cli#149]
Hi! When we run tx push we get the following error:
```
Error while creating resource, Post "/resources/": jsonapi does not handle redirects. You can access the Location header with `var e *jsonapi.RedirectError; errors.As(err, &e); e.Location`
```

Any idea how to bypass this?

**Comment by rlafuente** [comment]
Hi, I ran into the same issue. Did you find any way to deal with this, or is it just a pesky warning with no consequence?
