### ISSUE TITLE
Please document env vars

### ISSUE THREAD

**Issue by m3nu** [transifex/cli#151]
I see 2 env vars in the [source code](https://github.com/transifex/cli/blob/4a01798c960a765656a6919e91ea97626ce0baeb/cmd/tx/main.go#L37), but they don't seem to work and it will still ask for the token and write it to `~/.transifexrc`.

Would be great to fully run it with env vars only and document it in the README.

Thanks!

**Comment by codegaze** [comment]
@m3nu Of course we can add it to the documentation, but regarding your question could you please share a little bit more about how you set your environment variables, to unblock you?

Things I tried so far, just to see if everything behaves normally:
* Prefixing the variable `TX_TOKEN=randomstring tx status` ✅
* Adding the variable in profile file export TX_TOKEN="randomstring" ✅

**Comment by m3nu** [comment]
It works now. Not sure what was wrong before.

**Comment by codegaze** [comment]
Thanks for the update @m3nu! 💪
We will include the environment variables in the documentation and I will close this!

**Comment by codegaze** [comment]
Documentation updated!
