### ISSUE TITLE
Read: connection refused

### ISSUE THREAD

**Issue by alexandre-thauvin** [transifex/cli#152]
Hi,

I've freshly migrated to the CLI version from the older one.
I'm on archlinux, I have install this way:
`curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash`

`which tx`
`/bin/tx`

`tx --version`
`TX Client, version=1.6.4`

After a first `tx pull` I got prompted an API token to store it in the ` ~/.transifexrc` which I generated and paste.
`cat ~/.transifexrc `
```
[https://www.transifex.com]
rest_hostname = https://rest.api.transifex.com
token         = 1/MyToken
```

And getting the error when trying to pull since:

`my-project.my-resource - Get "https://rest.api.transifex.com/resources/o:org:p:project:r:resource": dial tcp: lookup rest.api.transifex.com on [::1]:53: read udp [::1]:58571->[::1]:53: read: connection refused`

Before I was already using an API token and it was working fine...

**Comment by codegaze** [comment]
Hello @alexandre-thauvin,

If you haven't done this, could you please try running `tx migrate` first? https://github.com/transifex/cli#migrating-from-older-versions-of-the-client

**Comment by alexandre-thauvin** [comment]
Hi, the `tx migrate` has already been ran on the project by one of my mate. I tried to rerun it, in order to make sure, it migrated successfully, but it's still failing to pull with the error mentioned above.

**Comment by alexandre-thauvin** [comment]
> Hello @alexandre-thauvin,
> 
> If you haven't done this, could you please try running `tx migrate` first? https://github.com/transifex/cli#migrating-from-older-versions-of-the-client

Hi, the tx migrate has already been ran on the project by one of my mate. I tried to rerun it, in order to make sure, it migrated successfully, but it's still failing to pull with the error mentioned above.

**Comment by codegaze** [comment]
Hmm, it's usually the migration command absence that results in these kinds of errors.

Ok, some questions just to try and better understand what might be going on:
* Did your mate managed to run the commands without an issue?
* Have you tried any other commands like `status`?
* Your config looks something like that right? Mostly referring to the first line with the id
```

[o:org_slug:p:proj_slu:r:resource_slug]
file_filter  = locales/<lang>file.txt
source_file  = file.txt
type         = TXT
minimum_perc = 0

```

**Comment by alexandre-thauvin** [comment]
My mate manager to run commands without any problems (he is on windows tho...)
tx status is working well
Yep the config was updated with the id that looks like that indeed.

**Comment by alexandre-thauvin** [comment]
> Hmm, it's usually the migration command absence that results in these kinds of errors.
> 
> Ok, some questions just to try and better understand what might be going on:
> 
> * Did your mate managed to run the commands without an issue?
> * Have you tried any other commands like `status`?
> * Your config looks something like that right? Mostly referring to the first line with the id
> 
> ```
> 
> [o:org_slug:p:proj_slu:r:resource_slug]
> file_filter  = locales/<lang>file.txt
> source_file  = file.txt
> type         = TXT
> minimum_perc = 0
> ```

My mate manager to run commands without any problems (he is on windows tho...)
tx status is working well
Yep the config was updated with the id that looks like that indeed.

**Comment by alexandre-thauvin** [comment]
I have another computer on which I work on this project and I managed to switch from the old client to the CLI version and everything works well, I just copied the transifexrc I quoted above and put a freshly generated token and I'm able to pull/push...

However it's still not working on my original machine (purpose of this issue)...
That's really weird...

**Comment by codegaze** [comment]
Thanks @alexandre-thauvin! :) 

At this point, I assume it might be an archlinux thing, so let's try at least this one. 
Could you please also run a `curl https://rest.api.transifex.com` and see if it can resolve the DNS?

**Comment by alexandre-thauvin** [comment]
> Thanks @alexandre-thauvin! :)
> 
> At this point, I assume it might be an archlinux thing, so let's try at least this one. Could you please also run a `curl https://rest.api.transifex.com` and see if it can resolve the DNS?

I'm gonna check that later on as I'm not on my original machine.
However my work machine (the one working) is on Manjaro (which is typically an archlinux with the manjaro layer on it...
Well I will try that at home tonight and keep you updated.

**Comment by codegaze** [comment]
@alexandre-thauvin I will close this one due to inactivity, but if the issue persists, please feel free to reopen!
