### ISSUE TITLE
tx init got 404 error in the last step.

### ISSUE THREAD

**Issue by tolerious** [transifex/cli#161]
Run the `rx init` command in the terminal.

after selecting the organization, I got an error like these:
```
[?] Select the organization to use [1-4]: 4
tx ERROR: 404 Client Error: Not Found for url: https://api.transifex.com/organizations/roscn/projects/
```

**Comment by codegaze** [comment]
Hello @tolerious!

Based on your output, it looks like you are using the [transifex-client](https://github.com/transifex/transifex-client) library which is deprecated. 

Migrating to the CLI of this repo will solve this issue.
