### ISSUE TITLE
can you release a deb for ubuntu. can not use now.

### ISSUE THREAD

**Issue by guohuadeng** [transifex/cli#162]
from your guide fail in ubuntu.

`curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash`

also we use 
`pip3 install transifex-client`

then run 
`tx pull`

all we get is error message 
need more than 1 value to unpack

how to fix, thanks

**Comment by codegaze** [comment]
Hello @guohuadeng,
You are trying to install two different packages. `transifex-client` is deprecated. 

Uninstalling the `transifex-client` and only use the first installation script (and all the instructions from this repo) should solve this problem.

**Comment by guohuadeng** [comment]
yes i try.
but can not run in  ubuntu

**Comment by guohuadeng** [comment]
after run and reboot
`curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash`

still can not run 
tx command in ubuntu.

**Comment by codegaze** [comment]
@guohuadeng Could you please copy/paste the output of the `curl` and `tx` commands to better understand the issue?
