### ISSUE TITLE
I have a few questions about the `tx` command.

### ISSUE THREAD

**Issue by Sopor** [transifex/cli#169]
I have a few questions about the `tx` command.

When doing a `tx pull` i can choose what i want to download with the option `--mode`.
Here are the values i can use: `reviewed`, `proofread`, `translator`, `untranslated`, `onlytranslated`, `onlyreviewed`and `onlyproofread`.
I do understand most of them, but i don't know the difference between
`reviewed`and `onlyreviewed`
`proofread`and `onlyproofread`
and how do i use `translator`?
I tried to use `-m translator`, but it seems to download as it was a normal download.

I have tried both `reviewed` and `onlyreviewed` and both are downloading 15 language files, but only three of them are reviewed to 100%. I don't know if `minimum_perc = 60` in the `config` file will override both these options or it will use 60 as a value too?
Shouldn't the command line options override the `config` file?

Can i put the other `--mode` options in the `config` file? So far i have only seen `minimum_perc` as an example.
I added `reviewed` to the config file, but then i got an error message: `key-value delimiter not found: reviewed`, but what should i add as value? When i run `tx pull -m reviewed -all` it will download 10 files, but if i run `tx pull -all` and write `reviewed = true` to the `config` file, it downloaded 11 files. Same thing if i write `reviewed = 60` (60 is the same as i have `minimum_perc `set to in the `config` file), 11 files get downloaded instead of 10. So, how do i use these `--mode` options in the `config` file when i don't know what value they need?

There should be some more information and examples on how to use these options on your help pages. 🙂

**Comment by chrisb-transifex** [comment]
Hello  , 
Thank you for contacting us. 
Please see the attached table . It should clear the field on how the modes in pull work. For the client pull command  see all rows that correspond to CLI . The modes refer to the strings that will be returned inside the files  depending on the mode. 

![image](https://user-images.githubusercontent.com/108664932/226318940-9bac2bf2-c88f-4236-8def-d7e23d101e76.png)

The modes work directly from the command line as so : tx pull  -m proofread for example. 

As for the setting inside the config file. This is not supported at the moment. We have forwarded the request to our product team and devs. In case we have any news we will update our documentation accordingly. 

Let me know if there is anything else i can do for you.

**Comment by codegaze** [comment]
On what Chris mentioned, please keep in mind that `onlytranslated` and `onlyreviewed` works on specific file formats. https://help.transifex.com/en/articles/6219670-introduction-to-file-formats#h_f64ebb95db

**Comment by kbairak** [comment]
Assuming the answers were satisfactory and closing the issue.
