### ISSUE TITLE
`tx migrate` crashes

### ISSUE THREAD

**Issue by mathaeus** [transifex/cli#18]
Hi, when executing `tx migrate` I get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x154bef2]

goroutine 1 [running]:
github.com/transifex/cli/internal/txlib.MigrateLegacyConfigFile(0xc0004bdad8, 0x0, 0x0, 0x0, 0x0, 0x179bbc0, 0xc000156000, 0x0, 0x0, 0x0, ...)
	/home/runner/work/cli/cli/internal/txlib/migrate.go:56 +0x312
github.com/transifex/cli/cmd/tx.Main.func2(0xc000176580, 0x1, 0x1)
	/home/runner/work/cli/cli/cmd/tx/main.go:74 +0x3b8
github.com/urfave/cli/v2.(*Command).Run(0xc0000cbd40, 0xc0001764c0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc00009dd40, 0x17a5f40, 0xc0000b6008, 0xc0000c0000, 0x2, 0x2, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/transifex/cli/cmd/tx.Main()
	/home/runner/work/cli/cli/cmd/tx/main.go:759 +0x219a
main.main()
	/home/runner/work/cli/cli/main.go:5 +0x25
```

I installed the client version `1.0.0` manually [following the doc](https://github.com/transifex/cli#installing-with-a-script-linuxmac). 
**I'm on Mac OS 12.2 (21D49) and using `zsh`.**

----

Is the `migrate` step able to migrate the `.tx/config` file? I'm not 100% sure reading the README.
We have quite a huge config with a lot of resources, therefore it'd be great if I don't need to change this manually and from what I understand I must change the old syntax from
`[project_slug.resource_slug]` to the new one:
`[o:org_slug:p:project_slug:r:resource_slug]`. 
Or does the migration contain any other change than how resources are referenced?

**Comment by kostasgeo** [comment]
Hi @mathaeus and thank you for the feeback!

You are correct that the `tx migrate` command aims at migrating the `.tx/config` file, but we wrongly made an assumption about the existence of the `.transifexrc` file, thus the issue. 

We have been informed by one of our customer support engineers that you have manually overcome the issue with the migration and you currently face a different one, but in any case the latest release of the client ([v1.0.1](https://github.com/transifex/cli/releases/tag/v1.0.1)) provides a fix for the migration.

**Comment by mathaeus** [comment]
Hi @kostasgeo, thanks for the update.

Yes, I did the migration by doing a find and replace with two regexes in the end. I guess your migration does something similar.
Since you released a new version, I will close this issue 👍
