### ISSUE TITLE
"tx push" does not find project when specifying a resource, but "tx pull" does

### ISSUE THREAD

**Issue by tim-heighes-fishbrain** [transifex/cli#180]
`$tx push -s my-project.my-resource` is returning an error:

```
# Getting info about resources

my-project.my-resource - Error while fetching stats, 404, not_found: No `Project` resource found with the identifier `o:org-1:p:my-project`
```

However, the equivalent pull `$tx pull my-project.my-resource` does find the project and resource, and completes successfully.

**Comment by tim-heighes-fishbrain** [comment]
This was a token issue. The server returns 404 for the project, instead of 401 Unauthorized. 🤷‍♂️

**Comment by rahu1ramesh** [comment]
> This was a token issue. The server returns 404 for the project, instead of 401 Unauthorized. 🤷‍♂️

Hey @tim-heighes-fishbrain , I'm struggling with the same issue and can't seem to wrap my head around why I'm getting a 404 when trying to push. Would be great if you can shed some light on how you resolved this issue.

**Comment by tim-heighes-fishbrain** [comment]
> > This was a token issue. The server returns 404 for the project, instead of 401 Unauthorized. 🤷‍♂️
> 
> 
> 
> Hey @tim-heighes-fishbrain , I'm struggling with the same issue and can't seem to wrap my head around why I'm getting a 404 when trying to push. Would be great if you can shed some light on how you resolved this issue.

I spoke with Transifex support who helped me through creating a new token.

**Comment by rahu1ramesh** [comment]
Thanks @tim-heighes-fishbrain.
