### ISSUE TITLE
Stuck in "Creating download job"

### ISSUE THREAD

**Issue by mart-e** [transifex/cli#188]
Hello,

I have a new resource and when I try to fetch the translations, it seems to be stuck.

```
$ tx pull --all --skip --workers 1 | cat
...
# Pulling files
... # existing resource
<project>.<new_resource> [ar] - Pulling file
<project>.<new_resource> [ar] - Creating download job
```
and just wait there forever.

Any idea?

**Comment by fardinmardani** [comment]
Hello, thank you for solving this problem and for being persistent
