### ISSUE TITLE
Keep getting prompted for token

### ISSUE THREAD

**Issue by inverse** [transifex/cli#208]
Running `1.6.10` and have token configured in `~/.transifexrc`

```
[https://app.transifex.com]
rest_hostname = https://rest.api.transifex.com
token         = <redacted>
```

Btu keep getting prompted to provide a whenever using the client.

**Comment by kulmann** [comment]
May I ask how you solved it? I'm having the same issue, back then with `1.6.10` and now still the same with `1.6.13`. My `~/.transifexrc` has the same content like yours.

**Comment by inverse** [comment]
@kulmann I had to do this change: https://github.com/TasmoAdmin/TasmoAdmin/pull/1062/files

**Comment by kulmann** [comment]
@inverse 
Ah nice! Same for me, the `.tx/config` in the project repo and my `.transifexrc` had a mismatch in the host name.

Just for the record, I just tried it with a random string, looks like it doesn't even need to be a url. As long as the `host = someString` in `.tx/config` matches the identifier `[someString]` in the `.transifexrc` file it seems to work just fine.

Anyway, thank you! Now I can remove the `TX_TOKEN` var from my `.zshrc` again 😎
