### ISSUE TITLE
--mode flag is giving permission denied error

### ISSUE THREAD

**Issue by mumarkhan999** [transifex/cli#28]
This flag was working fine with the older version (python CLI) but with the newer version it's giving permission denied error
No matter what value I choose for `--mode` it's giving the same error

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/42294172/157685429-e91a6764-1458-4e4d-b4b5-1717bf310f31.png">

**Comment by awais786** [comment]
Facing similar issue also.

**Comment by mumarkhan999** [comment]
@codegaze 
Need your help with this...

**Comment by codegaze** [comment]
Hey @mumarkhan999, thanks for bringing this matter to our attention! :) 
It seems to be an API issue and we need some time to figure things out. 
We will update when this is tackled.

**Comment by kostasgeo** [comment]
Hi @mumarkhan999 , @awais786! 

The `--mode` flag should now be working as expected. 
Feel free to test it and close the issue!

**Comment by mumarkhan999** [comment]
Hi @kostasgeo @codegaze  
Thanks for the response. I tested it on my local machine. 
The above-mentioned error is gone. But now we are getting the "pattern doesn't match" error for the `Chinese` language.
This was working fine previously with the old (python) client (I've tested it).

I'm attaching the screenshots of outputs for the new client
![image](https://user-images.githubusercontent.com/42294172/159266030-32c07d9e-1aca-4be4-8b16-f8ceaa06b0f7.png)

If I don't pull languages all at once it works fine

<img width="754" alt="image" src="https://user-images.githubusercontent.com/42294172/159266853-651f05ad-40cb-4f01-8594-ef05866bc450.png">

**Comment by kostasgeo** [comment]
Hi @mumarkhan999, 

We are glad to hear the `--mode` is now working as expected. 

The other error you refer to is related to the language code and the fact it has a dot in it. 
We 'll check this and update the issue as soon as possible.

**Comment by codegaze** [comment]
Hey @mumarkhan999,

Pulling/pushing for these kind of language patterns should work as expected! 

Thank you for reporting this and let's close this issue if everything is ok! :)

**Comment by mumarkhan999** [comment]
Hey, @codegaze  thanks for informing.
I've tested it. It's working fine now. 🏃‍♂️🏃‍♂️🏃‍♂️
Thanks for your support. 🤝🤝🤝
I'm closing this issue now. 🔒🔒🔒
