### ISSUE TITLE
tx migrate does not migrate source_lang

### ISSUE THREAD

**Issue by joeboyscout04** [transifex/cli#35]
The `tx migrate` command doesn't migrate a part of the file specifically that `source_lang` no longer is valid in the configuration, and `source_file` must be used instead.  At least providing a warning would be nice if it's not possible to migrate automatically. 

Using `source_lang` in the `.tx/config` and trying to `tx push` results in the error ` ERROR   could not find file ''. Aborting.`

In the `.tx/config`
Before:
```
[someproj.someresource]
file_filter = fastlane/metadata/<lang>/description.txt
source_lang = en-US
type = TXT
```

After:
```
[o:someorg:p:someproj:r:someresource]
file_filter = fastlane/metadata/<lang>/description.txt
source_lang = en-US
type        = TXT
```

What it should be:
```
[o:someorg:p:someproj:r:someresource]
file_filter = fastlane/metadata/<lang>/description.txt
source_file = fastlane/metadata/en-US/description.txt
type        = TXT
```

**Comment by codegaze** [comment]
Hey @joeboyscout04 thanks for bringing this to our attention!

I believe, we took the `source_file` as a given and this is why this part is missing. 

I guess a quick fix would be, during the migration script, to check for the `source_file` and if it doesn't exist add it in the config by using the `file_filter` and the `source_lang`.
