### ISSUE TITLE
-f overwrites --minimum-perc

### ISSUE THREAD

**Issue by HSorgYves** [transifex/cli#36]
Help suggests that -f only affects timestamps ("Force the download of the translationsfiles regardless of whether timestamps on the local computer are newer than those on the server (default: false)"). However -f also seems to affect --minimum-perc and download the translation no matter what...

**Comment by codegaze** [comment]
Hello @HSorgYves, thanks for reporting this!
As you noticed this issue should be fixed with the new release v1.1.0.
Feel free to check everything works as expected and close this issue :)

**Comment by HSorgYves** [comment]
Thanks.
