### ISSUE TITLE
onlytranslated mode not working for .resx files

### ISSUE THREAD

**Issue by bastianeicher** [transifex/cli#42]
According to the docs when downloading translations in the `onlytranslated` mode "the response will include the translated strings and the untranslated ones will be returned empty".

I ran `tx pull -l fr --mode onlytranslated` with the following `.tx/config`:

```
[main]
host = https://www.transifex.com
type = RESX

[o:eicher:p:0install-win:r:model]
source_file = Model.resx
file_filter = Model.<lang>.resx
```

The resulting file `Model.fr.resx` contained a mixture of translated French strings and untranslated English strings instead of only the French strings.

**Comment by antonismyl** [comment]
Hello Bastian,

I have already replied to you about this issue a few weeks earlier but in case you missed it I will repost my reply here.

> Hello again, Bastian,
> 
> I am Antonis, a support engineer from the Transifex support team.
> ﻿
> ﻿I looked into the issue that we talked about yesterday. I experienced the same behavior that you did, pulled the file and got all strings instead of just the translated ones. That led me to reference our documentation about .resx files and it looks like the onlytranslated and onlyreviewed flags are not supported for this file format. Fortunately, our product team is already aware and looking into expanding the supported file formats.
> 
> Until that time you can still use our API to receive your strings and filter them by status, depending on if it fits your workflow or not. You can find more information [here](https://developers.transifex.com/reference/get_resource-translations).
> 
> If you have any more questions please feel free to let me know!
> ﻿
> ﻿Kind regards,
> ﻿Antonis

You can view the relevant part of the documentation in the screenshot below:

![image](https://user-images.githubusercontent.com/102531293/167837239-f2ced009-a30c-480f-8e04-f13a2b5e1343.png)

**Comment by bastianeicher** [comment]
Thanks for the clarification. :)
