### ISSUE TITLE
tx migrate requires fancy API prompt

### ISSUE THREAD

**Issue by Daltz333** [transifex/cli#43]
`tx migrate` currently requires a API input instead of reading from the TX_TOKEN environment variable. We plan to use `tx migrate` in CI as we automatically generate our config file every build (waiting on a dependency to update it's format for the new expected config format). 

![image](https://user-images.githubusercontent.com/10674555/166127960-b5e40245-6258-4766-9b14-483eddc7a0ab.png)

**Comment by Docteh** [comment]
If you can change the config file a different way, the program will accept a TX_TOKEN. For the particular project I'm looking at the migration does this to the config file

```diff
diff --git a/dist/languages/.tx/config b/dist/languages/.tx/config
index 0d9b512ea..d55fc8ef2 100644
--- a/dist/languages/.tx/config
+++ b/dist/languages/.tx/config
@@ -1,8 +1,9 @@
 [main]
 host = https://www.transifex.com

-[yuzu.emulator]
+[o:yuzu-emulator:p:yuzu:r:emulator]
 file_filter = <lang>.ts
 source_file = en.ts
 source_lang = en
-type = QT
+type        = QT
+
```

**Comment by Daltz333** [comment]
I don't fully understand your response. Even in `tx pull` and `tx push` does not read from the environment variable `TX_CONFIG` and requires interaction, which is extremely hard to do in an automated CI environment.

**Comment by Docteh** [comment]
I was thinking the following sequence in CI

1. Modify  `.tx/config` without asking this transifex tool for a migration, possibly by copying a file onto it. [your file](https://github.com/wpilibsuite/frc-docs-translations/blob/main/.github/workflows/update-translations.yml) looks like a bit more complicated than the one I have on hand
Some regex? not sure on _how_, I just know what to change
`[frc-docs.index]` -> `[o:wpilib:p:frc-docs:r:index]`
2. Looks like you're setting TX_TOKEN
3. Do the `tx pull`  
4. Possibly revert the `.tx/config` script



I was able to do a `tx pull` with this new tool with just the `TX_TOKEN` and the `.tx/config`, I removed the $HOME/.transifexrc file in my testing.

**Comment by codegaze** [comment]
Hello @Daltz333,
The migration command was designed as a once off thing that a specific user would run in their machine and then add to the repo not something that would repeatedly run in the CI without any supervision.

Now, regarding your issue, @Docteh's alternative is an option. Have a script in your CI that changes the config with a regex on the fly and continue.

Another option off the top of my head would be:
* Do the whole process locally and have a different name for your new config file eg `config-next` or something and keep your old `config` for any use you want.
* When running commands in your CI include your different config like this:
```
tx --config=.tx/config-next pull
```

Apart from the `migrate` command, in any other case the environment variables should work. `TX_TOKEN`, `TX_HOSTNAME`, `TX_CACERT`. 

You are mentioning a `TX_CONFIG` which is not a variable we support.

Is this something that could solve your problem?

**Comment by codegaze** [comment]
Closing this one due to inactivity. @Daltz333 feel free to open it again if it's needed.
