### ISSUE TITLE
tx push errors with "No project"

### ISSUE THREAD

**Issue by Daltz333** [transifex/cli#46]
I've recently been in the process of updating [frc-docs-translations](https://github.com/wpilibsuite/frc-docs-translations) to support the new CLI. Using the [attached config file](https://www.toptal.com/developers/hastebin/rajoyiqewe.ini) (the repo config file has not been updated yet), I am getting the following freeze when attempting to run `tx push --source --skip`.

```
# Resource o:wpilib:p:frc-docs:r:docs--hardware--sensors--triangulating-rangefinders

 SUCCESS  Resource with slug 'docs--hardware--sensors--triangulating-rangefinders' found
  ERROR   Fetching stats: 404, not_found: No `Project` resource found with the identifier `o:wpilib:p:frc-docs`
```

**Comment by codegaze** [comment]
Hey @Daltz333, thanks for reporting this.

I have some questions to understand this problem better:
* Does this happen to all resources?
* What happens if you try to push this specific resource? Do you have the same output?

Also, please add the CLI version you are currently using. You can get it by running `tx --version` or `tx -v`

**Comment by Daltz333** [comment]
> Does this happen to all resources?

Yes

> What happens if you try to push this specific resource? Do you have the same output?

Yep

I'm running 1.1.0

**Comment by kbairak** [comment]
Hello @Daltz333 ,

Is there a chance that your API token does not have access to the project? Can you try running

```sh
export TRANSIFEX_TOKEN=...
curl -H "Authorization: Bearer $TRANSIFEX_TOKEN" https://rest.api.transifex.com/projects/o:wpilib:p:frc-docs
```

using the API token found in your `~/.transifexrc` file?

**Comment by codegaze** [comment]
@Daltz333 @kbairak I will close this for now, because of inactivity. Feel free to open it again if needed.

**Comment by rahu1ramesh** [comment]
> Hello @Daltz333 ,
> 
> Is there a chance that your API token does not have access to the project? Can you try running
> 
> ```shell
> export TRANSIFEX_TOKEN=...
> curl -H "Authorization: Bearer $TRANSIFEX_TOKEN" https://rest.api.transifex.com/projects/o:wpilib:p:frc-docs
> ```
> 
> using the API token found in your `~/.transifexrc` file?

Hello @kbairak,

I've encountered a similar issue (another issue was reported that describes a similar issue https://github.com/transifex/cli/issues/180). It appears to be connected to the API token I generated. I followed the curl command you provided, which successfully retrieved project details. I can pull the latest translations without any problems, but I'm experiencing failures when attempting `tx push`. Would be great if you can shed some light on how you resolved this issue.

**Comment by kronn** [comment]
We have a similar issue. The person can pull and push translations, but not the source. It seems that this is a permission issue with a correct, but unhelpful error message. Our main admin-account can push, the translator cannot.
