### ISSUE TITLE
Unable to pull all resources for a project

### ISSUE THREAD

**Issue by jordimas** [transifex/cli#51]
Hello. With the old Python client I was able to make:

tx init --host {0} --no-interactive'
tx config mapping-remote {0}'
tx --traceback pull -f -s -lca,ca_ES,en,en_GB'

And this enable my to download all resources for the project, however this with the new client does not seem possible.

I'm basically doing:

tx --hostname https://api.transifex.com --token XXXX init
tx pull --all -s

but does not work. How I can tell the client which project and to download all resources for a language?

Thanks,

**Comment by codegaze** [comment]
Hey @jordimas, thanks for the feedback!

This is something that the new CLI doesn't support yet, but it's in our plans to add this functionality in a future release in some way.

**Comment by kbairak** [comment]
Hey @jordimas ,

Although the new client does not support this functionality, this is something that you can relatively easily accomplish using our API and the Python API SDK. As an example:

```
➜  pip install --user transifex-python

➜  python maketxconfig.py

    Usage:

        python maketxconfig.py <api-token> <organization-slug> <project-slug> <locale-path> >> .tx/config

➜  python maketxconfig.py XXX kb_org kb_gh locale

    [o:kb_org:p:kb_gh:r:en-json--main]
    file_filter = locale/en-json--main/<lang>.json
    source_file = locale/en-json--main/en.json
    type = KEYVALUEJSON
    minimum_perc = 0

    [o:kb_org:p:kb_gh:r:locale-en-json--main]
    file_filter = locale/locale-en-json--main/<lang>.json
    source_file = locale/locale-en-json--main/en.json
    type = KEYVALUEJSON
    minimum_perc = 0
```

And here is the actual script:

```python
import configparser
import io
import sys

from transifex.api import transifex_api

usage = """Usage:

    python {} <api-token> <organization-slug> <project-slug> <locale-path> >> .tx/config
""".format(
    sys.argv[0]
)

try:
    token = sys.argv[1]
    organization_slug = sys.argv[2]
    project_slug = sys.argv[3]
    locale_path = sys.argv[4]
except IndexError:
    print(usage)
    sys.exit(1)

transifex_api.setup(auth=token)


def main():
    organization = transifex_api.Organization.get(slug=organization_slug)
    i18n_formats = {
        f.id: f
        for f in transifex_api.I18nFormat.filter(organization=organization).all()
    }
    project = organization.fetch("projects").get(slug=project_slug)
    source_language = project.fetch("source_language")

    config = configparser.ConfigParser()
    for resource in project.fetch("resources").all():
        i18n_format = i18n_formats[resource.i18n_format.id]
        ext = i18n_format.file_extensions[0]
        config[resource.id] = {
            "file_filter": f"{locale_path}/{resource.slug}/<lang>{ext}",
            "source_file": f"{locale_path}/{resource.slug}/{source_language.code}{ext}",
            "type": i18n_format.id,
            "minimum_perc": 0,
        }

    with io.StringIO() as f:
        config.write(f)
        f.seek(0)
        print(f.read())


if __name__ == "__main__":
    main()
```

**Comment by kbairak** [comment]
Hi @jordimas ,

The latest release [1.3.0](https://github.com/transifex/cli/releases/tag/v1.3.0) includes the `tx add remote` command which brings back this functionality.

Thank you for your feedback.

**Comment by jordimas** [comment]
Thanks so much.

When I do:

"tx add remote --file-filter 'translations/<project_slug>.<resource_slug>/<lang>.<ext>' https://www.transifex.com/myorganization/myproject/dashboard/"

I get an error:

unable to fetch project: Get "/projects/o:myorganization:p:myproject": unsupported protocol scheme ""

Will be possible to provide a step set of commands to download a sample project? (including setting the API key, host, and the pull)?
