### ISSUE TITLE
install script overwrites LICENSE.md if present in current directory?

### ISSUE THREAD

**Issue by mayel** [transifex/cli#53]

**Comment by mayel** [comment]
and README.md too

**Comment by mayel** [comment]
Yes, here are things I might expect instead:
- it could extract/install in a standard place, such as ~/.tx
- it could create a subfolder
- it could prompt before overriding any existing file

**Comment by kbairak** [comment]
Hi @mayel,

We fixed this 12 days ago but forgot to mention it. The installation script will now protect pre-existing files.

We normally wait for a release to occur before announcing that an issue is fixed, but the installation command as described in the README pulls the installation script from the `master` branch, this can be considered fixed now.

Thanks again for the feedback.
