### ISSUE TITLE
`tx pull` performs push task?

### ISSUE THREAD

**Issue by ByteHamster** [transifex/cli#56]
I just upgraded to `1.2.0` to test the parallel functionality. I am now getting an error message when pulling, which indicates that the client actually tries to push (and fails). I do not really care about the error itself but I am concerned that the `pull` task now also pushes. I do not want to upload the current state of the source files to Transifex. I only want to pull. Is this a deliberate behavior change? Before that, I tried  `1.0.3`, which apparently does not try to push something before pulling. At least it does not show error messages related to pushing.

```
$ tx pull --all --force --resources "xy" --minimum-perc=40
# Getting info about resources

xy - cannot push translations because the configuration file is missing the 'file_filter' field
[##############################] (1 / 1)
Aborted
```

**Comment by codegaze** [comment]
Hey @ByteHamster, thanks for bringing this to our attention. This is a message misuse.

In push and pull we use the `isFileFilterValid` function well... to check if the filter is valid. There is **no push functionality** there but the message is a left over from the latest refactoring we did.

Just for transparency, here is the code I'm referring to.
https://github.com/transifex/cli/blob/devel/internal/txlib/push.go#L733

We will try to have a fix with a new release the following days.

**Comment by kbairak** [comment]
Hello @ByteHamster ,

The latest release includes a fix for this issue. Thank you very much for the feedback.

**Comment by ByteHamster** [comment]
Thanks!
