### ISSUE TITLE
tx error with Github action

### ISSUE THREAD

**Issue by mendax1234** [transifex/cli#58]
l try to push and pull through github action automatically, but it goes wrong and below is the wrong message .
```
tx INFO: Updating /home/runner/.transifexrc file...
tx INFO: Using TX_TOKEN environment variable. Credentials won't be saved to .transifexrc.
tx ERROR: Authorization Required
tx ERROR: 
Error: Authentication failed. Please make sure your credentials are valid.
For more information, visit:
https://docs.transifex.com/client/client-configuration#-transifexrc.
```
l have checked my .transifexrc file and it is correct since l can use tx push -s from the local development environment. So what’s wrong with that? And here is my repo: [mendax1234/6940Swerve-docs: FRC Team 6940’s Swerve Documentation Powered by Read the Docs (github.com)](https://github.com/mendax1234/6940Swerve-docs)

**Comment by codegaze** [comment]
Hey @mendax1234,
I believe you are still using the [Python client](https://github.com/transifex/transifex-client). 
I would suggest closing this issue and start a new discussion in the repo for the old Python version of the client.

**Comment by mendax1234** [comment]
> Hey @mendax1234, I believe you are still using the [Python client](https://github.com/transifex/transifex-client). I would suggest closing this issue and start a new discussion in the repo for the old Python version of the client.

Sure , would you please give me some suggesstions on how to fix this bug? Thanks!

**Comment by mendax1234** [comment]
I have created a new issue. https://github.com/transifex/transifex-client/issues/342
