### ISSUE TITLE
Unable to install cli through install script on MacOS

### ISSUE THREAD

**Issue by MMartinDaniel** [transifex/cli#70]
Hi!,

I'm trying to install the cli client, but i'm being unable to install due to the following error: 

```
** Installing CLI from https://github.com/transifex/cli/releases/download/v1.2.1/tx-darwin-amd64.tar.gz

tar: Option --skip-old-files is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 4306k    0 17753    0     0  19416      0  0:03:47 --:--:--  0:03:47 19416
curl: (23) Failure writing output to destination
```
Tweaking the script while removing `--skip-old-files` does compress just fine or downloading the tar file manually and unzipping it manually works as well.

Any chance this could be fixed ?
Thanks

**Comment by codegaze** [comment]
Hey @MMartinDaniel, could you please share a bit more information about your system? Probably your `tar` version is more important.

From the message,`--skip-old-files is not supported` it looks that the flag is not supported which is a bit weird.

**Comment by Heyimlovinyou** [comment]
I don't know how to read *** ****** **** .I can't help but want n try to.
It's fuck idk how xplain without being evil bad but I waiting

**Comment by codegaze** [comment]
Thanks @MMartinDaniel, this helped a lot. 🙏

It looks like Mac OS X is using `bsdtar` which doesn't have a `--skip-old-files` but a `-k, --keep-old-files` flag (GNU tar).

We merged a new version that does that check and fallbacks to `bsdtar`, so everything should be ok!  

I’m closing this one, if you have any related issue after testing feel free to open it again!
