### ISSUE TITLE
Different behaviour of pull between new and old cli 

### ISSUE THREAD

**Issue by matteobaldelli** [transifex/cli#81]
Hi everyone, I just migrate to the new cli and I found out that when I am doing the `tx pull -a` I am not getting anymore the `po` file of the source language. There is a way to get it back?

Logs of old cli version
```
tx INFO:  -> nl_NL: web/translations/nl_NL/LC_MESSAGES/web.po
tx INFO:  -> fr_FR: web/translations/fr_FR/LC_MESSAGES/web.po
tx INFO:  -> en_GB: web/translations/en_GB/LC_MESSAGES/web.po
tx INFO:  -> de_DE: web/translations/de_DE/LC_MESSAGES/web.po
```

Logs of the new cli version
```
 SUCCESS  Target languages fetched

▀  Downloading translation file admin/translations/de_DE/LC_MESSAGES/admin.po
 ▀ Downloading translation file admin/translations/de_DE/LC_MESSAGES/admin.po
 ▄ Downloading translation file admin/translations/de_DE/LC_MESSAGES/admin.po
▄  Downloading translation file admin/translations/de_DE/LC_MESSAGES/admin.po
                                                                                
 SUCCESS  Translation file 'admin/translations/de_DE/LC_MESSAGES/admin.po' downloaded

▀  Downloading translation file admin/translations/fr_FR/LC_MESSAGES/admin.po
 ▀ Downloading translation file admin/translations/fr_FR/LC_MESSAGES/admin.po
                                                                                
 SUCCESS  Translation file 'admin/translations/fr_FR/LC_MESSAGES/admin.po' downloaded

▀  Downloading translation file admin/translations/nl_NL/LC_MESSAGES/admin.po
 ▀ Downloading translation file admin/translations/nl_NL/LC_MESSAGES/admin.po
                                                                                
 SUCCESS  Translation file 'admin/translations/nl_NL/LC_MESSAGES/admin.po' downloaded
```

**Comment by kbairak** [comment]
Hey @matteobaldelli ,

According to the [Readme](https://github.com/transifex/cli#pulling-files-from-transifex) you can

> If you use both the `-t/--translation` and the `-s/--source` flags, then you will pull both the source file, and the translation files.

**Comment by codegaze** [comment]
+1 on @kbairak's answer. Also, @matteobaldelli I believe you are using an older version of the CLI. 
I would suggest upgrading to 1.3.0 which has some performance optimizations, less output, and utilises parallelism.

**Comment by matteobaldelli** [comment]
Thanks both for the replay, @kbairak I tried to use the `-s` flag but I got a `.pot` file, I would like to have a `.po` file.
@codegaze thanks for the suggestion, I updated it after opening this issue

**Comment by kbairak** [comment]
Hey @matteobaldelli can you please send me the part of your `.tx/config` file where this resource is configured? I am curious about how you end up getting a `.pot` file.

**Comment by matteobaldelli** [comment]
Hey @kbairak, thanks for answering, I think you just found out why.

```
[main]
host = https://www.transifex.com

[o: organization:p:project:r:templates]
file_filter = web/translations/<lang>/LC_MESSAGES/web.po
source_file = web/translations/tx.pot
source_lang = en
type = PO
```

So I think I just need to change the source file extension
