### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by localjo** [transifex/cli#82]
I'm trying to upload new strings to be translated to an existing project. The old command I ran was:

```
txjs-cli push '{,!(node_modules|dist)/**/}*.{js,jsx,ts,tsx}' --token=$TRANSIFEX_TOKEN --secret=$TRANSIFEX_SECRET
```

But that doesn't seem to work anymore (it runs, and says it uploaded the strings, but they don't appear in the project dashboard).

So I figured, rather than debugging the old command, I'd use the new CLI. But I can't figure out how the new CLI works. I installed it, ran `tx config`. The next step wasn't clear, so I tried to run `tx add`, but it asks for a "source" file. I didn't see any documentation about what a "source" file is, but when I try `{,!(node_modules|dist)/**/}*.{js,jsx,ts,tsx}`, it says "you need to add a Source File that exists".

I think my problem here is that the documentation is unclear. I just want to scan and upload strings like I did before. What do I need to configure to do so, and what are the correct steps?

**Comment by codegaze** [comment]
Hey @localjo, closing this in favor of https://github.com/transifex/transifex-javascript/issues/150. 
This CLI is used for file projects.
