### ISSUE TITLE
tx pull odoo-15, raise error.

### ISSUE THREAD

**Issue by jeffery9** [transifex/cli#83]
'''
tx pull -a
# Getting info about resources

odoo-15-l10n.l10n_be - Get "/resources/o::p:odoo-15-l10n:r:l10n_be": unsupported protocol scheme ""
odoo-15-l10n.l10n_ca - Get "/resources/o::p:odoo-15-l10n:r:l10n_ca": unsupported protocol scheme ""
odoo-15-l10n.l10n_ch - Get "/resources/o::p:odoo-15-l10n:r:l10n_ch": unsupported protocol scheme ""
odoo-15-l10n.l10n_cn - Get "/resources/o::p:odoo-15-l10n:r:l10n_cn": unsupported protocol scheme ""
odoo-15-l10n.l10n_eg_edi_eta - Get "/resources/o::p:odoo-15-l10n:r:l10n_eg_edi_eta": unsupported protocol scheme ""
[##############################] (266 / 266)
Aborted
'''

the project is 
```
head .tx/config
[main]
host = https://www.transifex.com
type = PO

[odoo-15.base]
file_filter = odoo/addons/base/i18n/<lang>.po
source_file = odoo/addons/base/i18n/base.pot
source_lang = en

```

**Comment by codegaze** [comment]
Hello @jeffery9, it seems that you are using this client but you haven't migrated to the new config yet. :) 
The first thing to do is to run `tx migrate` but please also take a look at the [migration guide](https://github.com/transifex/cli#migrating-from-older-versions-of-the-client).

**Comment by codegaze** [comment]
Hey @jeffery9 I will close this one. Feel free to reopen it, if the issue remains.
