### ISSUE TITLE
504 Gateway Time-out error written to `.stringsdict` files

### ISSUE THREAD

**Issue by mr-v** [transifex/cli#84]
## Issue

About 9 hours ago our automation was pulling `.stringsdict` files. The downloads completed successfully, but the content of some of them was overwritten with:

```html
 <html>
 <head><title>504 Gateway Time-out</title></head>
 <body>
 <center><h1>504 Gateway Time-out</h1></center>
 </body>
 </html>
```

Logs from pulling (FWIW I changed the filename here):

```
[00:23:04]: ▸ x-ios.Intents [da] - Pulling file
1029
[00:23:04]: ▸ x-ios.Intents [da] - Creating download job
...
[00:23:05]: ▸ x-ios.Intents [da] - Done
```

- version: `1.3.0`
- command: `tx pull -f`

## What's expected

The command should fail on encountering the error.

**Comment by codegaze** [comment]
Hello @mr-v, we appreciate the report and the information to better understand this! 
We will have a new release tomorrow with a fix, so I will update this issue to let you know.

**Comment by codegaze** [comment]
Hey @mr-v, 
Thank you again for this report. Updating to the latest version ([v1.3.1](https://github.com/transifex/cli/releases/tag/v1.3.1)) should solve this issue.

I will close this issue for now. Feel free to open it again if something seems off.

**Comment by mr-v** [comment]
Excellent, thank you for addressing this so quickly!
