### ISSUE TITLE
file_filter no longer allows the usage of the <lang> tag more than once

### ISSUE THREAD

**Issue by HSorgYves** [transifex/cli#89]
Developing for Joomla!, it makes sense to put language files into language packages. Thus a file filter like
`file_filter = files_projectname_<lang>/<lang>.com_projectname.ini`
is very useful. Is it possible to reintroduce this feature?

**Comment by kbairak** [comment]
@HSorgYves The issue has been fixed. It will be included in the next release, but we will do a pass through the rest of the open issues first to include as many fixes in the release. You can try building the CLI from the `devel` branch if you want, following the instructions on our README.

Thank you for bringing this to our attention.

**Comment by YvesKreis** [comment]
@kbairak Works fine. Thanks!

**Comment by HSorgYves** [comment]
@kbairak Works fine. Thanks!
